### PR TITLE
fix: issue #8

### PR DESCRIPTION
**Pull request by yoution**

### CODE REVIEW

**Comment by nqviet** [comment]
Hi, it is just a normal promise rejection of NullPointerException.
It is safe to uncatch.

**Comment by nqviet** [comment]
to mute it, just do: 
Untitled

**Comment by yoution** [comment]
@nqviet  yes, you can catch the error, but if you catch the error this place will make other request not send, like `groups` request

**Comment by nqviet** [comment]
the problem this issue is mentioning is that (in point of view of a developer): 
- not login
- click Earn Icon in navbar menu on top
- see that the page is blank.

**Comment by luizrrodrigues** [comment]
Closing this because we have a better implementation from Challenge Listing part 2.

**Pull request closed without merging**
